import nvFormatA from 'nv-format/esm';
var nFI = nvFormatA();
console.log( 'import nvFormatA from \'nv-format/esm\'' );
console.log( 'nvFormatA(300, "200")', nFI(300, 200) );
console.log( 'nvFormatA(300, "x")', nFI(300, "x") );
console.log( 'nvFormatA(300, "dddd")', nFI(300, "dddd") );
console.log( 'nvFormatA(300, "dddd.ddd")', nFI(300, "dddd.ddd") );
console.log( 'everything seems to work' );
console.log( '************************' );
import nvFormatB from 'nv-format/esm/nv-format.js';
var nFI = nvFormatB();
console.log( 'import nvFormatB from \'nv-format/esm/nv-format.js\'' );
console.log( 'nvFormatB(300, "200")', nFI(300, 200) );
console.log( 'nvFormatB(300, "x")', nFI(300, "x") );
console.log( 'nvFormatB(300, "dddd")', nFI(300, "dddd") );
console.log( 'nvFormatB(300, "dddd.ddd")', nFI(300, "dddd.ddd") );
console.log( 'everything seems to work' );
console.log( '************************' );
console.log( '(nvFormatA === nvFormatB) is ' + (nvFormatA === nvFormatB) );
